# Generated by Django 5.2.8 on 2025-11-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechoice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_choices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='employeechoice',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='menus.menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='employeechoice',
            unique_together={('employee', 'menu')},
        ),
    ]
